<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cloc3
 * Date: Thu, 30 Jan 2014 15:35:35 +0100
 */

$conf['title'] = 'Liceo Paschini';
$conf['start'] = 'liceo paschini';
$conf['lang'] = 'it';
$conf['template'] = 'paschiniBase';
$conf['license'] = 'cc-by-sa';
$conf['recent'] = 50;
$conf['recent_days'] = 365;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['manager'] = 'cloc3,ivano';
$conf['rememberme'] = 0;
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['registernotify'] = 'ziapanocchia@gmail.com';
$conf['mailfrom'] = '"dokuwikiki_2013-14"<ziapannocchia@gmail.com>';
$conf['mailprefix'] = '"dokuwiki_2013-14 Liceo Paschini"';
$conf['sitemap'] = 5;
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['fnencode'] = 'utf-8';
$conf['gzip_output'] = 1;
$conf['compression'] = 'bz2';
$conf['plugin']['cleanup']['runautomatically'] = 1;
$conf['plugin']['cleanup']['mediaatticnoexonly'] = 0;
$conf['plugin']['cleanup']['metaage'] = 60*60*24*3;
$conf['plugin']['clearhistory']['autoclearenabled'] = 1;
$conf['plugin']['clearhistory']['autoclearonlynocomment'] = 1;

// end auto-generated content
